backend:
  name: github
  repo: Ezra-Siton-UIX/raz-zafrir
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "site"
    label: "Site Content"
    files:
      - name: "hero"
        label: "Hero Heading"
        file: "content/site.json"
        fields:
          - { label: "Main Text", name: "heading_main", widget: "string" }
          - { label: "Highlighted Text (Green)", name: "heading_highlight", widget: "string" }
